language: python
python:
  - "2.7"
  - "3.6"
env:
  - PYRAMID_VERSION="pyramid>=1.3,<1.4"
  - PYRAMID_VERSION="pyramid>=1.8,<1.9"
# command to install dependencies
install:
  - "easy_install -U setuptools"
  - "pip install flake8"
  - "pip install $PYRAMID_VERSION"
  - "pip install -e .[tests]"
before_script: "flake8 pyramid_genshi --ignore=E501,W291,W293"
# command to run tests
script: "python setup.py nosetests -sv"
